// All user-facing UI strings live here (CLAUDE.md hard rule #4).
// No hardcoded Hebrew inside components.

export const strings = {
  appName: "OurTrip",
  appDescription: "מרכז הפיקוד של הטיול המשפחתי",

  nav: {
    today: "היום",
    itinerary: "מסלול",
    budget: "תקציב",
    documents: "מסמכים",
    more: "עוד",
  },

  today: {
    emptyTitle: "עוד אין מה להציג",
    emptyBody: "כשנתחיל להזין את המסלול, כאן יופיע כל מה שקורה היום.",
    noDay: "אין יום מתוכנן במסלול להיום",
    bookingsToday: "הזמנות להיום",
    quickExpense: "הוספת הוצאה",
    quickItinerary: "למסלול",
    snapshotFrom: "עדכני לתאריך",
  },

  documents: {
    upload: "העלאת מסמך",
    edit: "עריכת מסמך",
    searchPlaceholder: "חיפוש מסמך…",
    tags: {
      passport: "דרכונים",
      insurance: "ביטוח",
      vaccine: "חיסונים",
      visa: "ויזות",
      other: "אחר",
    } as Record<string, string>,
    allTags: "הכל",
    docTitle: "שם המסמך",
    tag: "תגית",
    notes: "הערות",
    file: "קובץ",
    uploading: "מעלה…",
    empty: "עוד אין מסמכים בכספת",
    noResults: "לא נמצאו מסמכים",
    deleteConfirm: "למחוק את המסמך? גם העותק במכשיר יימחק",
    open: "פתיחת מסמך",
    openFailed: "אין עותק שמור של המסמך במכשיר",
    offlineToggle: "זמין ללא אינטרנט",
    offlineSaved: "המסמך נשמר במכשיר",
    offlineRemoved: "העותק הוסר מהמכשיר",
  },

  emergency: {
    title: "חירום",
    sos: "SOS",
    numbers: "מספרי חירום",
    police: "משטרה",
    ambulance: "אמבולנס",
    fire: "מכבי אש",
    embassy: "שגרירות ישראל",
    phone: "טלפון",
    address: "כתובת",
    insurance: "ביטוח נסיעות",
    insuranceCompany: "חברת ביטוח",
    insurancePolicy: "מס׳ פוליסה",
    insurancePhone: "מוקד חירום של הביטוח",
    hotel: "המלון הנוכחי",
    hotelName: "שם המלון",
    medical: "מידע רפואי",
    editTitle: "עריכת דף חירום",
    emptyPage: "עוד לא הוזן מידע חירום למדינה הזו",
    noCountries: "אין עדיין מדינות — הוסיפו ימים עם מדינה במסלול או צרו דף חדש",
    addCountry: "מדינה חדשה",
    countryCode: "קוד מדינה (2 אותיות, למשל JP)",
    saved: "דף החירום נשמר",
  },

  placeholders: {
    comingSoon: "בקרוב…",
    documents: "כספת המסמכים תיבנה בספרינט 4",
    more: "הגדרות, דף חירום ועוד — בהמשך",
  },

  budget: {
    totalSpent: "סה״כ הוצאות",
    totalPlanned: "מתוך תקציב",
    burnRate: "קצב יומי",
    projection: "צפי לסוף הטיול",
    tripNotStarted: "הטיול טרם התחיל",
    perDay: "ליום",
    categories: "קטגוריות",
    editPlanned: "עריכת תקציב מתוכנן",
    plannedAmount: "סכום מתוכנן (₪)",
    addExpense: "הוספת הוצאה",
    editExpense: "עריכת הוצאה",
    amount: "סכום",
    currency: "מטבע",
    category: "קטגוריה",
    categoryTapHint: "בחירת קטגוריה שומרת את ההוצאה",
    description: "תיאור (לא חובה)",
    date: "תאריך",
    expenseSaved: "ההוצאה נשמרה",
    expenseQueued: "אין חיבור — ההוצאה תסונכרן אוטומטית כשיהיה אינטרנט",
    deleteExpenseConfirm: "למחוק את ההוצאה?",
    recentExpenses: "הוצאות אחרונות",
    emptyExpenses: "עוד אין הוצאות",
    fxError: "לא הצלחנו להמיר את המטבע — נסו שוב",
    converterTitle: "המרת מטבע",
    converterRateLine: "לפי השער היומי",
    converterNoRate: "אין שער זמין למטבע הזה",
  },

  checklists: {
    title: "רשימות",
    lists: "רשימות",
    templates: "תבניות",
    addList: "רשימה חדשה",
    listName: "שם הרשימה",
    saveAsTemplate: "שמירה כתבנית",
    empty: "עוד אין רשימות — מתחילים ברשימה חדשה",
    emptyTemplates: "אין תבניות",
    useTemplate: "יצירת רשימה מהתבנית",
    listCreated: "הרשימה נוצרה",
    deleteListConfirm: "למחוק את הרשימה ואת כל הפריטים שבה?",
    templateInUse: "אי אפשר למחוק תבנית שנוצרו ממנה רשימות",
    addItemPlaceholder: "מה להוסיף?",
    add: "הוספה",
    editItem: "עריכת פריט",
    itemLabel: "פריט",
    assignee: "אחראי/ת",
    deleteItemConfirm: "למחוק את הפריט?",
    emptyItems: "אין פריטים ברשימה",
    back: "חזרה לרשימות",
  },

  more: {
    menuChecklists: "רשימות",
    menuEmergency: "דף חירום",
    menuMap: "מפה",
    menuPhrasebook: "שיחון",
    menuJournal: "יומן",
    menuPhotos: "תמונות",
    menuPocket: "דמי כיס",
    menuKids: "ילדים ומכשירים",
    menuGuests: "אורחים",
    menuMessages: "הקיר המשפחתי",
    menuRecommend: "מה בסביבה",
    menuNotifications: "התראות",
  },

  recommend: {
    title: "מה בסביבה",
    subtitle: "המלצות ידידותיות לילדים בסביבה — מסעדות, אטרקציות וטיפים",
    useLocation: "מהמיקום הנוכחי",
    useDay: "לפי יום במסלול",
    pickDay: "בחירת יום",
    find: "חיפוש המלצות",
    finding: "מחפשים המלצות…",
    empty: "לא נמצאו המלצות — נסו מיקום אחר",
    error: "לא הצלחנו להביא המלצות כרגע. נסו שוב.",
    needLocation: "צריך לאפשר מיקום או לבחור יום עם מיקום במסלול",
    locationDenied: "הגישה למיקום נחסמה — אפשר לבחור יום מהמסלול במקום",
    addToItinerary: "הוספה למסלול",
    addedToItinerary: "נוסף למסלול!",
    saveMaybe: "שמירה לאולי",
    savedMaybe: "נשמר לרשימת האולי",
    openInMaps: "פתחו במפות",
    maybeListTitle: "רשימת האולי",
    maybeEmpty: "עוד לא שמרתם המלצות",
    remove: "הסרה",
    addDayPrompt: "לאיזה יום להוסיף?",
    noDays: "אין ימים במסלול — הוסיפו יום קודם",
    ownersOnly: "התכונה זמינה להורים בלבד",
  },

  notifications: {
    title: "התראות",
    subtitle: "קבלו עדכונים חשובים גם כשהאפליקציה סגורה",
    enable: "הפעלת התראות",
    working: "מפעילים…",
    enabled: "התראות פעילות במכשיר הזה ✓",
    disable: "כיבוי התראות",
    denied: "ההתראות חסומות — צריך לאפשר אותן בהגדרות הדפדפן",
    unsupported: "הדפדפן הזה לא תומך בהתראות",
    missingKey: "מפתח ההתראות (VAPID) לא הוגדר בשרת עדיין",
    error: "לא הצלחנו להפעיל התראות — נסו שוב",
    whatTitle: "מה נשלח",
    whatWeather: "☔ התראת גשם ביום עם פעילות בחוץ",
    whatCheckin: "🛫 תזכורת צ'ק-אין 24 שעות לפני טיסה",
    whatWall: "💬 הודעה חדשה בקיר המשפחתי",
    whatPhoto: "📷 תמונה חדשה שממתינה לאישור (להורים)",
    iosTitle: "כדי לקבל התראות ב-iPhone / iPad",
    iosStep1: "פותחים את האפליקציה ב-Safari",
    iosStep2: "מקישים על כפתור השיתוף ולמטה",
    iosStep3: "בוחרים ״הוספה למסך הבית״",
    iosStep4: "פותחים את OurTrip מהמסך הבית — ואז מפעילים כאן התראות",
  },

  weather: {
    clear: "בהיר",
    partlyCloudy: "מעונן חלקית",
    cloudy: "מעונן",
    fog: "ערפילי",
    drizzle: "טפטוף",
    rain: "גשום",
    showers: "ממטרים",
    snow: "שלג",
    thunderstorm: "סופות רעמים",
    rainChance: "סיכוי לגשם",
    rainAlert: "צפוי גשם היום ויש פעילויות בחוץ — כדאי להיערך",
  },

  map: {
    title: "מפה",
    dayFilterAll: "כל הימים",
    navigate: "ניווט",
    addPin: "הוספת סימון",
    pinLabel: "שם הסימון",
    pinHint: "לחיצה ארוכה על המפה מוסיפה סימון",
    deletePinConfirm: "למחוק את הסימון?",
    routes: "מסלולים שמורים",
    drawRoute: "ציור מסלול",
    drawingHint: "לחצו על המפה להוספת נקודות למסלול",
    finishRoute: "שמירת המסלול",
    cancelDraw: "ביטול הציור",
    routeName: "שם המסלול",
    deleteRouteConfirm: "למחוק את המסלול?",
    routeSaved: "המסלול נשמר",
    noKey: "מפתח Google Maps לא מוגדר — המפה לא זמינה",
    car: "הרכב שלנו",
    carSave: "שמירת מיקום הרכב",
    carSaved: "מיקום הרכב נשמר",
    carSavedAt: "נשמר",
    carNavigate: "ניווט לרכב",
    carPhoto: "צילום החניה (לא חובה)",
    carNone: "עוד לא נשמר מיקום רכב",
    carLocationError: "לא הצלחנו לאתר את המיקום — בדקו הרשאות מיקום",
    carDeleteConfirm: "למחוק את מיקום הרכב?",
  },

  phrasebook: {
    title: "שיחון",
    empty: "עוד אין שפות בשיחון — מוסיפים שפה ראשונה",
    addLanguage: "שפה חדשה",
    languageSelect: "בחירת שפה",
    customCode: "או קוד שפה (ISO)",
    generate: "יצירת שיחון",
    generating: "יוצר שיחון… זה לוקח בערך דקה",
    generated: "השיחון נוצר",
    generateFailed: "יצירת השיחון נכשלה — נסו שוב",
    regenerate: "יצירה מחדש",
    showToLocal: "הצגה למקומי",
    showToLocalHint: "לחיצה על משפט מציגה אותו גדול — נוח להראות למקומיים",
    phonetic: "הגייה",
    emptyLanguage: "אין משפטים בשפה הזו",
  },

  common: {
    save: "שמירה",
    cancel: "ביטול",
    delete: "מחיקה",
    close: "סגירה",
    loading: "טוען…",
    error: "משהו השתבש, נסו שוב",
    none: "ללא",
  },

  itinerary: {
    tabPlan: "מסלול",
    tabBookings: "הזמנות",
    addDay: "הוספת יום",
    editDay: "עריכת יום",
    date: "תאריך",
    location: "מיקום",
    countryCode: "קוד מדינה",
    countryCodeHint: "שתי אותיות, למשל JP",
    notes: "הערות",
    deleteDayConfirm: "למחוק את היום ואת כל הפעילויות שבו?",
    duplicateDate: "כבר קיים יום בתאריך הזה",
    emptyDays: "עוד אין ימים במסלול — מתחילים בהוספת יום",
    emptyDayItems: "אין פעילויות ביום הזה",
    addItem: "הוספת פעילות",
    editItem: "עריכת פעילות",
    itemTitle: "מה עושים?",
    startTime: "שעת התחלה",
    endTime: "שעת סיום",
    outdoor: "פעילות בחוץ",
    status: "סטטוס",
    statusPlanned: "מתוכנן",
    statusDone: "בוצע",
    statusCancelled: "בוטל",
    linkedBooking: "הזמנה מקושרת",
    deleteItemConfirm: "למחוק את הפעילות?",
    moveItem: "העברה ליום אחר",
    movePickDay: "לאיזה יום להעביר?",
    dragHandle: "גרירה לשינוי סדר",
  },

  bookings: {
    add: "הוספת הזמנה",
    edit: "עריכת הזמנה",
    title: "שם ההזמנה",
    type: "סוג",
    types: {
      flight: "טיסה",
      hotel: "מלון",
      train: "רכבת",
      attraction: "אטרקציה",
      car_rental: "השכרת רכב",
      other: "אחר",
    },
    startDate: "תאריך התחלה",
    endDate: "תאריך סיום",
    confirmationCode: "קוד אישור",
    cost: "עלות",
    currency: "מטבע",
    status: "סטטוס",
    statuses: {
      booked: "הוזמן",
      paid: "שולם",
      cancelled: "בוטל",
    },
    linkUrl: "קישור להזמנה",
    openLink: "פתיחת קישור",
    notes: "הערות",
    flightNumber: "מספר טיסה",
    terminal: "טרמינל",
    checkIn: "שעת צ׳ק-אין",
    checkOut: "שעת צ׳ק-אאוט",
    address: "כתובת",
    attachFile: "צירוף קובץ",
    replaceFile: "החלפת קובץ",
    openFile: "פתיחת קובץ",
    uploading: "מעלה קובץ…",
    fileAttached: "הקובץ צורף",
    empty: "עוד אין הזמנות",
    deleteConfirm: "למחוק את ההזמנה?",
    deleteLinked: "אי אפשר למחוק — ההזמנה מקושרת לפעילות או להוצאה",
    addToDay: "הוספה למסלול",
    addToDayPick: "לאיזה יום להוסיף?",
    addedToDay: "נוסף למסלול",
    expensePromptTitle: "לרשום הוצאה בתקציב?",
    expensePromptBody: "להזמנה יש עלות — אפשר לרשום אותה כהוצאה מקושרת.",
    expenseCategory: "קטגוריה",
    expenseCreate: "רישום הוצאה",
    expenseSkip: "לא עכשיו",
    expenseCreated: "ההוצאה נרשמה בתקציב",
    expenseFxError: "לא הצלחנו להמיר את המטבע — ההוצאה לא נרשמה",
  },

  places: {
    searchPlaceholder: "חיפוש מקום…",
  },

  kidNav: {
    journal: "יומן",
    photos: "תמונות",
    pocket: "דמי כיס",
    phrasebook: "שיחון",
    messages: "הודעות",
  },

  guestNav: {
    photos: "תמונות",
    journal: "יומן",
    map: "מפה",
    messages: "הודעות",
  },

  wall: {
    title: "הקיר המשפחתי",
    placeholder: "כותבים משהו למשפחה…",
    send: "שליחה",
    empty: "עוד אין הודעות — כתבו את הראשונה!",
    me: "אני",
  },

  guests: {
    title: "אורחים",
    invite: "הזמנת אורח/ת",
    email: "אימייל",
    name: "שם",
    send: "שליחת הזמנה",
    emailed: "ההזמנה נשלחה במייל",
    linkReady: "הקישור מוכן — שלחו אותו לאורח (למשל בוואטסאפ)",
    copyLink: "העתקת הקישור",
    copied: "הקישור הועתק",
    empty: "עוד לא הוזמנו אורחים",
    active: "פעיל/ה",
    revoked: "הוסר/ה",
    revoke: "הסרת גישה",
    revokeConfirm: "להסיר את הגישה של האורח/ת? אפשר להזמין שוב בכל שלב",
    reinvite: "הזמנה מחדש",
  },

  guestHome: {
    welcome: "ברוכים הבאים לפורטל הטיול!",
    subtitle: "כאן רואים תמונות, יומן מסע ומפה של איפה שכבר היינו",
    tilePhotos: "תמונות",
    tileJournal: "יומן מסע",
    tileMap: "איפה היינו",
    tileWall: "הקיר המשפחתי",
  },

  kidLogin: {
    title: "כניסת ילדים",
    codeTitle: "חיבור הטאבלט",
    codeHint: "מבקשים מאמא או אבא קוד, ומקלידים אותו כאן",
    codePlaceholder: "הקוד",
    connect: "חיבור",
    invalidCode: "הקוד לא נכון או שפג תוקפו — מבקשים קוד חדש",
    pinTitle: "שלום",
    pinHint: "מקלידים את הקוד הסודי",
    wrongPin: "הקוד הסודי לא נכון",
    attemptsLeft: "נסיונות שנשארו",
    locked: "המכשיר נעול לכמה דקות — מנסים שוב מאוחר יותר",
    unlockError: "משהו השתבש — מנסים שוב",
    backToParents: "כניסת הורים",
    delete: "מחיקה",
  },

  kidHome: {
    hello: "שלום",
    whereToday: "איפה אנחנו היום?",
    noLocation: "יום חופשי!",
    journalPrompt: "מה היה הכי כיף היום?",
    journalCta: "כותבים ביומן",
    tilePhotos: "התמונות שלנו",
    tilePocket: "דמי הכיס שלי",
    tilePhrasebook: "שיחון",
  },

  journal: {
    title: "יומן",
    prompt: "מה היה הכי כיף היום?",
    placeholder: "כותבים כאן…",
    mood: "איך היה היום?",
    addPhoto: "הוספת תמונה",
    publish: "שמירה ביומן",
    saved: "נשמר ביומן!",
    empty: "עוד אין רשומות ביומן",
    deleteConfirm: "למחוק את הרשומה?",
    sharedWithGuests: "משותף עם האורחים",
    shareToggle: "שיתוף עם אורחים",
  },

  photos: {
    title: "תמונות",
    upload: "העלאת תמונה",
    uploading: "מעלה…",
    uploaded: "התמונה הועלתה! היא תופיע אחרי שאמא או אבא יאשרו",
    uploadedOwner: "התמונה הועלתה",
    empty: "עוד אין תמונות",
    caption: "כיתוב (לא חובה)",
    pending: "ממתין לאישור",
    rejected: "לא אושר",
    approvalQueue: "ממתינות לאישור",
    approve: "אישור",
    reject: "דחייה",
    shareToggle: "שיתוף עם אורחים",
    shared: "משותף",
    deleteConfirm: "למחוק את התמונה?",
  },

  pocket: {
    title: "דמי כיס",
    allowance: "דמי כיס לטיול",
    spent: "יצא",
    left: "נשאר",
    addExpense: "קניתי משהו!",
    whatBought: "מה קנית?",
    howMuch: "כמה עלה? (₪)",
    save: "רישום",
    saved: "נרשם!",
    empty: "עוד לא נרשמו קניות",
    noAllowance: "עוד לא הוגדרו דמי כיס — מבקשים מאמא או אבא",
    setAllowance: "עדכון דמי כיס",
    deleteConfirm: "למחוק את הרישום?",
    infoNote: "דמי כיס לא נספרים בתקציב המשפחתי",
  },

  kids: {
    title: "ילדים ומכשירים",
    addKid: "הוספת ילד/ה",
    kidName: "שם",
    noKids: "עוד לא הוגדרו ילדים",
    generateCode: "יצירת קוד חיבור",
    pinLabel: "קוד סודי לטאבלט (4-6 ספרות)",
    codeReady: "הקוד מוכן — מקלידים אותו בטאבלט תוך 15 דקות",
    deviceActive: "מכשיר מחובר",
    deviceLocked: "נעול זמנית",
    deviceRevoked: "נותק",
    noDevice: "אין מכשיר מחובר",
    revoke: "ניתוק המכשיר",
    revokeConfirm: "לנתק את המכשיר? יידרש קוד חיבור חדש",
    connectedAt: "חובר",
  },

  auth: {
    signIn: "כניסה עם Google",
    signOut: "יציאה",
    notAllowedTitle: "אין הרשאה",
    notAllowedBody: "החשבון הזה לא מורשה להיכנס לאפליקציה. נסו עם חשבון אחר.",
    missingEnv: "חסרים משתני סביבה של Supabase — ראו .env.local.example",
  },

  offline: {
    banner: "אין חיבור לאינטרנט — חלק מהמסכים לא זמינים",
    synced: "הרישומים שנשמרו במצב לא מקוון סונכרנו",
    syncFailed: "חלק מההוצאות שנרשמו לא מקוון לא נשמרו — כדאי לרשום אותן מחדש",
    fromCache: "מוצג מהעותק השמור במכשיר",
  },
} as const;
