// All user-facing UI strings live here (CLAUDE.md hard rule #4).
// No hardcoded Hebrew inside components.

export const strings = {
  appName: "OurTrip",
  appDescription: "מרכז הפיקוד של הטיול המשפחתי",

  nav: {
    today: "היום",
    itinerary: "מסלול",
    budget: "תקציב",
    documents: "מסמכים",
    more: "עוד",
  },

  today: {
    emptyTitle: "עוד אין מה להציג",
    emptyBody: "כשנתחיל להזין את המסלול, כאן יופיע כל מה שקורה היום.",
    noDay: "אין יום מתוכנן במסלול להיום",
    bookingsToday: "הזמנות להיום",
    quickExpense: "הוספת הוצאה",
    quickItinerary: "למסלול",
    snapshotFrom: "עדכני לתאריך",
  },

  documents: {
    upload: "העלאת מסמך",
    edit: "עריכת מסמך",
    searchPlaceholder: "חיפוש מסמך…",
    tags: {
      passport: "דרכונים",
      insurance: "ביטוח",
      vaccine: "חיסונים",
      visa: "ויזות",
      other: "אחר",
    } as Record<string, string>,
    allTags: "הכל",
    docTitle: "שם המסמך",
    tag: "תגית",
    notes: "הערות",
    file: "קובץ",
    uploading: "מעלה…",
    empty: "עוד אין מסמכים בכספת",
    noResults: "לא נמצאו מסמכים",
    deleteConfirm: "למחוק את המסמך? גם העותק במכשיר יימחק",
    open: "פתיחת מסמך",
    openFailed: "אין עותק שמור של המסמך במכשיר",
    offlineToggle: "זמין ללא אינטרנט",
    offlineSaved: "המסמך נשמר במכשיר",
    offlineRemoved: "העותק הוסר מהמכשיר",
  },

  emergency: {
    title: "חירום",
    sos: "SOS",
    numbers: "מספרי חירום",
    police: "משטרה",
    ambulance: "אמבולנס",
    fire: "מכבי אש",
    embassy: "שגרירות ישראל",
    phone: "טלפון",
    address: "כתובת",
    insurance: "ביטוח נסיעות",
    insuranceCompany: "חברת ביטוח",
    insurancePolicy: "מס׳ פוליסה",
    insurancePhone: "מוקד חירום של הביטוח",
    hotel: "המלון הנוכחי",
    hotelName: "שם המלון",
    medical: "מידע רפואי",
    editTitle: "עריכת דף חירום",
    emptyPage: "עוד לא הוזן מידע חירום למדינה הזו",
    noCountries: "אין עדיין מדינות — הוסיפו ימים עם מדינה במסלול או צרו דף חדש",
    addCountry: "מדינה חדשה",
    countryCode: "קוד מדינה (2 אותיות, למשל JP)",
    saved: "דף החירום נשמר",
  },

  placeholders: {
    comingSoon: "בקרוב…",
    documents: "כספת המסמכים תיבנה בספרינט 4",
    more: "הגדרות, דף חירום ועוד — בהמשך",
  },

  budget: {
    totalSpent: "סה״כ הוצאות",
    totalPlanned: "מתוך תקציב",
    burnRate: "קצב יומי",
    projection: "צפי לסוף הטיול",
    tripNotStarted: "הטיול טרם התחיל",
    perDay: "ליום",
    categories: "קטגוריות",
    editPlanned: "עריכת תקציב מתוכנן",
    plannedAmount: "סכום מתוכנן (₪)",
    addExpense: "הוספת הוצאה",
    editExpense: "עריכת הוצאה",
    amount: "סכום",
    currency: "מטבע",
    category: "קטגוריה",
    categoryTapHint: "בחירת קטגוריה שומרת את ההוצאה",
    description: "תיאור (לא חובה)",
    date: "תאריך",
    expenseSaved: "ההוצאה נשמרה",
    expenseQueued: "אין חיבור — ההוצאה תסונכרן אוטומטית כשיהיה אינטרנט",
    deleteExpenseConfirm: "למחוק את ההוצאה?",
    recentExpenses: "הוצאות אחרונות",
    emptyExpenses: "עוד אין הוצאות",
    fxError: "לא הצלחנו להמיר את המטבע — נסו שוב",
    converterTitle: "המרת מטבע",
    converterRateLine: "לפי השער היומי",
    converterNoRate: "אין שער זמין למטבע הזה",
  },

  checklists: {
    title: "רשימות",
    lists: "רשימות",
    templates: "תבניות",
    addList: "רשימה חדשה",
    listName: "שם הרשימה",
    saveAsTemplate: "שמירה כתבנית",
    empty: "עוד אין רשימות — מתחילים ברשימה חדשה",
    emptyTemplates: "אין תבניות",
    useTemplate: "יצירת רשימה מהתבנית",
    listCreated: "הרשימה נוצרה",
    deleteListConfirm: "למחוק את הרשימה ואת כל הפריטים שבה?",
    templateInUse: "אי אפשר למחוק תבנית שנוצרו ממנה רשימות",
    addItemPlaceholder: "מה להוסיף?",
    add: "הוספה",
    editItem: "עריכת פריט",
    itemLabel: "פריט",
    assignee: "אחראי/ת",
    deleteItemConfirm: "למחוק את הפריט?",
    emptyItems: "אין פריטים ברשימה",
    back: "חזרה לרשימות",
  },

  more: {
    menuChecklists: "רשימות",
    menuEmergency: "דף חירום",
  },

  common: {
    save: "שמירה",
    cancel: "ביטול",
    delete: "מחיקה",
    close: "סגירה",
    loading: "טוען…",
    error: "משהו השתבש, נסו שוב",
    none: "ללא",
  },

  itinerary: {
    tabPlan: "מסלול",
    tabBookings: "הזמנות",
    addDay: "הוספת יום",
    editDay: "עריכת יום",
    date: "תאריך",
    location: "מיקום",
    countryCode: "קוד מדינה",
    countryCodeHint: "שתי אותיות, למשל JP",
    notes: "הערות",
    deleteDayConfirm: "למחוק את היום ואת כל הפעילויות שבו?",
    duplicateDate: "כבר קיים יום בתאריך הזה",
    emptyDays: "עוד אין ימים במסלול — מתחילים בהוספת יום",
    emptyDayItems: "אין פעילויות ביום הזה",
    addItem: "הוספת פעילות",
    editItem: "עריכת פעילות",
    itemTitle: "מה עושים?",
    startTime: "שעת התחלה",
    endTime: "שעת סיום",
    outdoor: "פעילות בחוץ",
    status: "סטטוס",
    statusPlanned: "מתוכנן",
    statusDone: "בוצע",
    statusCancelled: "בוטל",
    linkedBooking: "הזמנה מקושרת",
    deleteItemConfirm: "למחוק את הפעילות?",
    moveItem: "העברה ליום אחר",
    movePickDay: "לאיזה יום להעביר?",
    dragHandle: "גרירה לשינוי סדר",
  },

  bookings: {
    add: "הוספת הזמנה",
    edit: "עריכת הזמנה",
    title: "שם ההזמנה",
    type: "סוג",
    types: {
      flight: "טיסה",
      hotel: "מלון",
      train: "רכבת",
      attraction: "אטרקציה",
      car_rental: "השכרת רכב",
      other: "אחר",
    },
    startDate: "תאריך התחלה",
    endDate: "תאריך סיום",
    confirmationCode: "קוד אישור",
    cost: "עלות",
    currency: "מטבע",
    status: "סטטוס",
    statuses: {
      booked: "הוזמן",
      paid: "שולם",
      cancelled: "בוטל",
    },
    linkUrl: "קישור להזמנה",
    openLink: "פתיחת קישור",
    notes: "הערות",
    flightNumber: "מספר טיסה",
    terminal: "טרמינל",
    checkIn: "שעת צ׳ק-אין",
    checkOut: "שעת צ׳ק-אאוט",
    address: "כתובת",
    attachFile: "צירוף קובץ",
    replaceFile: "החלפת קובץ",
    openFile: "פתיחת קובץ",
    uploading: "מעלה קובץ…",
    fileAttached: "הקובץ צורף",
    empty: "עוד אין הזמנות",
    deleteConfirm: "למחוק את ההזמנה?",
    deleteLinked: "אי אפשר למחוק — ההזמנה מקושרת לפעילות או להוצאה",
    addToDay: "הוספה למסלול",
    addToDayPick: "לאיזה יום להוסיף?",
    addedToDay: "נוסף למסלול",
    expensePromptTitle: "לרשום הוצאה בתקציב?",
    expensePromptBody: "להזמנה יש עלות — אפשר לרשום אותה כהוצאה מקושרת.",
    expenseCategory: "קטגוריה",
    expenseCreate: "רישום הוצאה",
    expenseSkip: "לא עכשיו",
    expenseCreated: "ההוצאה נרשמה בתקציב",
    expenseFxError: "לא הצלחנו להמיר את המטבע — ההוצאה לא נרשמה",
  },

  places: {
    searchPlaceholder: "חיפוש מקום…",
  },

  auth: {
    signIn: "כניסה עם Google",
    signOut: "יציאה",
    notAllowedTitle: "אין הרשאה",
    notAllowedBody: "החשבון הזה לא מורשה להיכנס לאפליקציה. נסו עם חשבון אחר.",
    missingEnv: "חסרים משתני סביבה של Supabase — ראו .env.local.example",
  },

  offline: {
    banner: "אין חיבור לאינטרנט — חלק מהמסכים לא זמינים",
    synced: "הרישומים שנשמרו במצב לא מקוון סונכרנו",
    fromCache: "מוצג מהעותק השמור במכשיר",
  },
} as const;
